import { useEffect, useState } from 'react';
import { wallPath } from '../core';
import type { EditCommand, Floor, Opening, Point2, Selection } from '../types';
import { closedBoundary, editedProvenance, objectLabel, pathLength, uid } from './geometry';

type Props = { floor: Floor; selection: Selection | null; onSelect: (selection: Selection | null) => void; onEdit: (commands: EditCommand[]) => void; disabled: boolean; onBoundary: (roomID?: string) => void };
function Nudge({ move, disabled }: { move: (delta: Point2) => void; disabled: boolean }) {
  return <div className="spatial-nudge" aria-label="Small position adjustments"><button disabled={disabled} aria-label="Move up" onClick={() => move({ x: 0, z: -0.05 })}>↑</button><div><button disabled={disabled} aria-label="Move left" onClick={() => move({ x: -0.05, z: 0 })}>←</button><span>Adjust</span><button disabled={disabled} aria-label="Move right" onClick={() => move({ x: 0.05, z: 0 })}>→</button></div><button disabled={disabled} aria-label="Move down" onClick={() => move({ x: 0, z: 0.05 })}>↓</button></div>;
}
export function Inspector({ floor, selection, onSelect, onEdit, disabled, onBoundary }: Props) {
  const [label, setLabel] = useState('');
  const [openingKind, setOpeningKind] = useState<Opening['kind']>('door');
  const [vertex, setVertex] = useState(0);
  const select = (kind: Selection['kind'], objectID: string) => onSelect({ floorID: floor.id, kind, objectID });
  useEffect(() => { setLabel(selection?.kind === 'room' ? floor.rooms.find(r => r.id === selection.objectID)?.label ?? '' : selection?.kind === 'area' ? floor.areas?.find(a => a.id === selection.objectID)?.label ?? '' : ''); setVertex(0); }, [selection?.objectID, selection?.kind, floor.rooms.find(r=>r.id===selection?.objectID)?.label, floor.areas?.find(a=>a.id===selection?.objectID)?.label]);
  if (!selection) return <aside className="spatial-inspector"><div className="spatial-eyebrow">DETAILS</div><h2>Make it your space.</h2><p>Select a wall, opening or room to make a correction. The plan and model share every change.</p><div className="spatial-inspector-tip"><span className="spatial-tip-symbol">↖</span><strong>One layout. Every view.</strong><p>Drag selected corners and walls in the plan, or use the adjustment buttons for a small correction.</p></div><p className="spatial-caption">Geometric drawing only. Measurements are unverified.</p></aside>;
  const node = floor.nodes.find(n => n.id === selection.objectID), wall = floor.walls.find(w => w.id === selection.objectID), opening = floor.openings.find(o => o.id === selection.objectID), room = floor.rooms.find(r => r.id === selection.objectID), area = floor.areas?.find(a => a.id === selection.objectID);
  const apply = (command: EditCommand) => onEdit([command]);
  const chooseAction = (value: string, action: (id: string) => void) => { if (value) action(value); };
  return <aside className="spatial-inspector"><div className="spatial-inspector-heading"><div><div className="spatial-eyebrow">{selection.kind === 'node' ? 'CORNER' : selection.kind.toUpperCase()}</div><h2>{objectLabel(floor, selection)}</h2></div><button aria-label="Clear selection" className="spatial-icon-button" onClick={() => onSelect(null)}>×</button></div>
    <fieldset disabled={disabled}>
    {(selection.kind === 'wall' && wall || selection.kind === 'node' && node) && <section><h3>Position</h3><Nudge disabled={disabled} move={delta => { if (selection.kind === 'node' && node) apply({ type: 'moveNode', floorID: floor.id, nodeID: node.id, point: { x: node.point.x + delta.x, z: node.point.z + delta.z } }); else if (wall) apply({ type: 'moveWall', floorID: floor.id, wallID: wall.id, translation: delta }); }} /><p className="spatial-caption">Small display adjustments. Check the result against the property.</p></section>}
    {selection.kind === 'node' && node && <section><h3>Connections</h3><label>Connect to corner<select value="" onChange={event => chooseAction(event.target.value, id => apply({ type: 'mergeNodes', floorID: floor.id, sourceNodeID: node.id, targetNodeID: id }))}><option value="">Choose a corner…</option>{floor.nodes.filter(n => n.id !== node.id).map(n => <option key={n.id} value={n.id}>{objectLabel(floor, { floorID: floor.id, kind: 'node', objectID: n.id })}</option>)}</select></label><label>Disconnect from wall<select value="" onChange={event => chooseAction(event.target.value, id => apply({ type: 'disconnectNode', floorID: floor.id, wallID: id, nodeID: node.id, newNodeID: uid() }))}><option value="">Choose a wall…</option>{floor.walls.filter(w => w.nodeIDs.includes(node.id)).map(w => <option key={w.id} value={w.id}>{objectLabel(floor, { floorID: floor.id, kind: 'wall', objectID: w.id })}</option>)}</select></label><p className="spatial-caption">Connections use explicit shared corners. Invalid or broken room boundaries are rejected.</p></section>}
    {selection.kind === 'wall' && wall && <><section><h3>Opening</h3><label>Type<select value={openingKind} onChange={event => setOpeningKind(event.target.value as Opening['kind'])}><option value="door">Door</option><option value="window">Window</option><option value="passage">Passage</option></select></label><button className="spatial-full-button" onClick={() => { const length = pathLength(wallPath(floor, wall)), width = Math.min(0.9, length / 3), bottom = openingKind === 'window' ? wall.height * 0.35 : 0; const created: Opening = { id: uid(), kind: openingKind, wallID: wall.id, offset: (length - width) / 2, width, bottom, height: openingKind === 'window' ? wall.height * 0.4 : Math.min(2.1, wall.height), provenance: editedProvenance() }; apply({ type: 'addOpening', floorID: floor.id, opening: created }); select('opening', created.id); }}>+ Add {openingKind}</button><p className="spatial-caption">Creates a real cutout in the shared wall geometry.</p></section><section><h3>Wall topology</h3><button className="spatial-full-button" onClick={() => apply({ type: 'splitWall', floorID: floor.id, wallID: wall.id, offset: pathLength(wallPath(floor, wall)) / 2, newWallID: uid(), newNodeID: uid() })}>Split at midpoint</button><label>Join another wall<select value="" onChange={event => chooseAction(event.target.value, id => apply({ type: 'joinWalls', floorID: floor.id, firstWallID: wall.id, secondWallID: id }))}><option value="">Choose a wall…</option>{floor.walls.filter(w => w.id !== wall.id).map(w => <option key={w.id} value={w.id}>{objectLabel(floor, { floorID: floor.id, kind: 'wall', objectID: w.id })}</option>)}</select></label><div className="spatial-button-stack">{wall.nodeIDs.map(id => <button key={id} onClick={() => select('node', id)}>Edit {objectLabel(floor, { floorID: floor.id, kind: 'node', objectID: id }).toLowerCase()}</button>)}</div><button className="spatial-danger spatial-full-button" onClick={() => { if (confirm('Delete this wall? The edit is rejected if a room or opening still depends on it. You can undo a successful deletion.')) apply({ type: 'deleteWall', floorID: floor.id, wallID: wall.id }); }}>Delete wall</button></section><p className="spatial-caption">Source: {wall.provenance.origin}. Height: {wall.heightBasis}.</p></>}
    {selection.kind === 'opening' && opening && <><section><label>Opening type<select value={opening.kind} onChange={event => apply({ type: 'updateOpening', floorID: floor.id, opening: { ...opening, kind: event.target.value as Opening['kind'] } })}><option value="door">Door</option><option value="window">Window</option><option value="passage">Passage</option></select></label><h3>Along the wall</h3><div className="spatial-button-pair"><button onClick={() => apply({ type: 'moveOpening', floorID: floor.id, openingID: opening.id, offset: Math.max(0, opening.offset - 0.05) })}>← Earlier</button><button onClick={() => apply({ type: 'moveOpening', floorID: floor.id, openingID: opening.id, offset: opening.offset + 0.05 })}>Later →</button></div><h3>Shape</h3>{([['width', 'Narrower', 'Wider'], ['height', 'Shorter', 'Taller'], ['bottom', 'Lower', 'Raise']] as const).map(([key, less, more]) => <div className="spatial-button-pair" key={key}><button onClick={() => apply({ type: 'updateOpening', floorID: floor.id, opening: { ...opening, [key]: opening[key] - 0.05 } })}>{less}</button><button onClick={() => apply({ type: 'updateOpening', floorID: floor.id, opening: { ...opening, [key]: opening[key] + 0.05 } })}>{more}</button></div>)}<label>Move to host wall<select value={opening.wallID} onChange={event => { const host = floor.walls.find(w => w.id === event.target.value)!; apply({ type: 'updateOpening', floorID: floor.id, opening: { ...opening, wallID: host.id, offset: (pathLength(wallPath(floor, host)) - opening.width) / 2 } }); }}>{floor.walls.map(w => <option key={w.id} value={w.id}>{objectLabel(floor, { floorID: floor.id, kind: 'wall', objectID: w.id })}</option>)}</select></label><p className="spatial-caption">The opening must fit its host without overlapping another opening. Windows never act as walking portals.</p><button className="spatial-danger spatial-full-button" onClick={() => apply({ type: 'deleteOpening', floorID: floor.id, openingID: opening.id })}>Delete opening</button></section></>}
    {selection.kind === 'room' && room && <><section><form onSubmit={event => { event.preventDefault(); apply({ type: 'renameRoom', floorID: floor.id, roomID: room.id, label }); }}><label>Room name<input value={label} maxLength={256} onChange={event => setLabel(event.target.value)} /></label><button className="spatial-full-button" type="submit" disabled={!label.trim() || label === room.label}>Save name</button></form></section><section><h3>Room boundary</h3><button className="spatial-full-button" onClick={() => onBoundary(room.id)}>Edit boundary walls</button><label>Split with partition<select value="" onChange={event => chooseAction(event.target.value, id => apply({ type: 'splitRoom', floorID: floor.id, roomID: room.id, dividerWallID: id, newRoomID: uid(), newLabel: 'New room' }))}><option value="">Choose a drawn partition…</option>{floor.walls.filter(w => !floor.rooms.some(r => r.boundary.some(b => b.wallID === w.id))).map(w => <option key={w.id} value={w.id}>{objectLabel(floor, { floorID: floor.id, kind: 'wall', objectID: w.id })}</option>)}</select></label><label>Merge with adjacent room<select value="" onChange={event => chooseAction(event.target.value, id => { if (confirm('Merge these rooms and remove their shared physical partition and its openings? Undo can restore the earlier layout.')) apply({ type: 'mergeRooms', floorID: floor.id, firstRoomID: room.id, secondRoomID: id }); })}><option value="">Choose a room…</option>{floor.rooms.filter(r => r.id !== room.id && r.boundary.some(b => room.boundary.some(a => a.wallID === b.wallID))).map(r => <option key={r.id} value={r.id}>{r.label}</option>)}</select></label><p className="spatial-caption">A room describes a closed physical region. Use an area for a label or work zone inside it.</p><button className="spatial-danger spatial-full-button" onClick={() => { if (confirm('Remove this room region and label? Its walls will remain.')) apply({ type: 'deleteRoom', floorID: floor.id, roomID: room.id }); }}>Remove room region</button></section></>}
    {selection.kind === 'area' && area && <><section><form onSubmit={event => { event.preventDefault(); apply({ type: 'setArea', floorID: floor.id, area: { ...area, label } }); }}><label>Area name<input value={label} maxLength={256} onChange={event => setLabel(event.target.value)} /></label><button className="spatial-full-button" type="submit" disabled={!label.trim() || label === area.label}>Save name</button></form><label>Adjust polygon corner<select value={vertex} onChange={event => setVertex(Number(event.target.value))}>{area.polygon.map((_, index) => <option key={index} value={index}>Area corner {index + 1}</option>)}</select></label><Nudge disabled={disabled} move={delta => apply({ type: 'setArea', floorID: floor.id, area: { ...area, polygon: area.polygon.map((p, i) => i === vertex ? { x: p.x + delta.x, z: p.z + delta.z } : p), provenance: { ...area.provenance, origin: 'edited' } } })} /><p className="spatial-caption">A semantic area is a label and polygon, not a physical wall or verified area quantity.</p><button className="spatial-danger spatial-full-button" onClick={() => apply({ type: 'deleteArea', floorID: floor.id, areaID: area.id })}>Delete area</button></section></>}
    </fieldset>
  </aside>;
}

export function BoundaryForm({ floor, roomID, onSave }: { floor: Floor; roomID?: string; onSave: (commands: EditCommand[]) => void }) {
  const room = floor.rooms.find(r => r.id === roomID);
  const [label, setLabel] = useState(room?.label ?? 'New room');
  const [walls, setWalls] = useState<string[]>(room?.boundary.map(b => b.wallID) ?? []);
  const [error, setError] = useState('');
  return <form onSubmit={event => { event.preventDefault(); try { const boundary = closedBoundary(floor, walls); onSave(roomID ? [{ type: 'setRoomBoundary', floorID: floor.id, roomID, boundary }, { type: 'renameRoom', floorID: floor.id, roomID, label }] : [{ type: 'addRoom', floorID: floor.id, room: { id: uid(), label, boundary } }]); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }}><label>Room name<input value={label} onChange={event => setLabel(event.target.value)} maxLength={256} /></label><p>Select walls that connect into one closed boundary. Shared corner identities determine the order; gaps are never guessed.</p><div className="spatial-wall-checks">{floor.walls.map(wall => <label key={wall.id}><input type="checkbox" checked={walls.includes(wall.id)} onChange={event => setWalls(event.target.checked ? [...walls, wall.id] : walls.filter(id => id !== wall.id))} />{objectLabel(floor, { floorID: floor.id, kind: 'wall', objectID: wall.id })}</label>)}</div>{error && <p role="alert" className="spatial-error-text">{error}</p>}<button className="spatial-primary spatial-full-button" disabled={walls.length < 3 || !label.trim()} type="submit">{roomID ? 'Save boundary' : 'Create room'}</button></form>;
}
