import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { applyCommands } from '../core';
import { SpatialWebStore, exportRevision, importDocument } from '../data';
import { captureCapabilities, captureRoom } from '../capture';
import { saveExport } from '../exportDelivery';
import type { EditCommand, ExportFormat, Floor, FrozenRevision, Selection, SpatialDocument, StoredWorkspace, WorkspaceContext, WorkspaceSummary } from '../types';
import { FloorplanCanvas, type CanvasTool } from './FloorplanCanvas';
import { ModelViewport } from './ModelViewport';
import { BoundaryForm, Inspector } from './Inspector';
import { freshDocument, objectLabel, syntheticDocument, uid } from './geometry';
import { reviewItems } from './review';
import './workspace.css';

const standalone: WorkspaceContext = { mode: 'standalone', namespace: 'auxilium-spatial-local-v1' };
const formats: { id: ExportFormat; label: string; description: string; scope: 'all' | 'floor' | 'one' }[] = [
  { id: 'pdf', label: 'PDF drawing set', description: 'Clean architectural pages for review', scope: 'all' },
  { id: 'png', label: 'PNG drawing', description: 'An image of the selected floor', scope: 'floor' },
  { id: 'svg', label: 'SVG line drawing', description: 'Scalable vector line art', scope: 'floor' },
  { id: 'glb', label: 'GLB geometric model', description: 'Portable 3D geometry for this floor', scope: 'floor' },
  { id: 'geometry', label: 'Geometry JSON', description: 'The canonical graph and every floor', scope: 'all' },
  { id: 'scene', label: 'Scene JSON', description: 'Derived 3D faces and semantic edges', scope: 'floor' },
  { id: 'local-document', label: 'Complete local document', description: 'All floors in a validated recovery package', scope: 'all' },
  { id: 'bundle', label: 'Single-floor exchange bundle', description: 'Versioned geometry, scene and manifest', scope: 'one' },
];
const errorText = (cause: unknown) => cause instanceof Error ? cause.message : String(cause);
function Mark() { return <svg width="27" height="30" viewBox="0 0 27 30" fill="none" aria-hidden="true"><path d="M3 24V9L13.5 3L24 9V24L13.5 28L3 24Z" stroke="currentColor" strokeWidth="1.7"/><path d="M3 9L13.5 15L24 9M13.5 15V28M8 12V22M19 12V22" stroke="currentColor" strokeWidth="1.5"/></svg>; }
function Dialog({ title, onClose, children, error }: { title: string; onClose: () => void; children: ReactNode; error?: string }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const active = window.document.activeElement as HTMLElement | null; ref.current?.showModal(); return () => active?.focus(); }, []);
  return <dialog ref={ref} className="spatial-dialog" onCancel={event => { event.preventDefault(); onClose(); }}><div className="spatial-dialog-title"><h2>{title}</h2><button aria-label="Close dialog" onClick={onClose}>×</button></div>{error&&<p className="spatial-error-text" role="alert">{error}</p>}{children}</dialog>;
}
export function SpatialWorkspace({ context = standalone }: { context?: WorkspaceContext }) {
  const [library, setLibrary] = useState<WorkspaceSummary[]>([]);
  const [stored, setStored] = useState<StoredWorkspace | null>(null);
  const [floorID, setFloorID] = useState('');
  const [selection, setSelection] = useState<Selection | null>(null);
  const [mode, setMode] = useState<'plan' | 'model'>('plan');
  const [tool, setTool] = useState<CanvasTool>('select');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [accessDenied, setAccessDenied] = useState(false);
  const [loading, setLoading] = useState(true);
  const [pending, setPending] = useState<{ expected: number; commands: EditCommand[]; preview: SpatialDocument } | null>(null);
  const [modal, setModal] = useState<'new' | 'export' | 'room' | 'floor' | 'revisions' | 'capture' | 'review' | null>(null);
  const [boundaryRoom, setBoundaryRoom] = useState<string>();
  const [revisions, setRevisions] = useState<FrozenRevision[]>([]);
  const [frozen, setFrozen] = useState<FrozenRevision | null>(null);
  const [exportFormat, setExportFormat] = useState<ExportFormat>('pdf');
  const [exportScope, setExportScope] = useState<'all' | 'floor'>('all');
  const [exportFloorID, setExportFloorID] = useState('');
  const [mobilePanel, setMobilePanel] = useState<'canvas' | 'objects' | 'details'>('canvas');
  const [capability, setCapability] = useState<{ available: boolean; reason?: string }>({ available: false, reason: 'Checking capture availability.' });
  const importInput = useRef<HTMLInputElement>(null);
  const storeRef = useRef<SpatialWebStore | null>(null);
  const contextRef = useRef(context); contextRef.current = context;
  const generation = useRef(0);
  const busyRef = useRef(false);
  const current = pending?.preview ?? stored?.document;
  const floor = current?.floors.find(f => f.id === floorID) ?? current?.floors[0];
  const disabled = busy || !!pending || accessDenied;
  const issues = useMemo(() => current && floor ? reviewItems(current, floor) : [], [current, floor]);
  async function access() { const ctx = contextRef.current; if (ctx.mode !== 'standalone') { try { await ctx.assertAccess(); } catch (cause) { setAccessDenied(true); setStored(null); setLibrary([]); setPending(null); setSelection(null); setFrozen(null); setRevisions([]); throw cause; } } }
  async function run<T>(work: (store: SpatialWebStore) => Promise<T>): Promise<T | undefined> {
    if (busyRef.current || accessDenied) return;
    const gen = generation.current;
    busyRef.current = true; setBusy(true); setError('');
    try { await access(); const store = storeRef.current; if (!store || gen !== generation.current) return; const value = await work(store); await access(); if (gen !== generation.current) return; return value; } catch (cause) { if (gen === generation.current) setError(errorText(cause)); return; } finally { if (gen === generation.current) { busyRef.current = false; setBusy(false); } }
  }
  useEffect(() => {
    const gen = ++generation.current; const store = new SpatialWebStore(context.namespace); storeRef.current = store;
    setStored(null);setPending(null);setSelection(null);setFrozen(null);setRevisions([]);setAccessDenied(false);setLoading(true);setError('');setLibrary([]);setBusy(false);busyRef.current=false;
    void (async()=>{try{await access();const entries=await store.list();if(gen===generation.current)setLibrary(entries);}catch(cause){if(gen===generation.current)setError(errorText(cause));}finally{if(gen===generation.current)setLoading(false);}})();
    const recheck = () => { if (window.document.visibilityState === 'visible') void access().catch(cause=>setError(errorText(cause))); };
    window.document.addEventListener('visibilitychange',recheck);
    return()=>{generation.current++;store.close();if(storeRef.current===store)storeRef.current=null;window.document.removeEventListener('visibilitychange',recheck);};
  },[context.namespace,context.mode]);
  useEffect(()=>{let active=true;void captureCapabilities().then(value=>{if(active)setCapability(value);}).catch(cause=>{if(active)setCapability({available:false,reason:errorText(cause)});});return()=>{active=false;};},[]);
  useEffect(()=>{const listener=(event:BeforeUnloadEvent)=>{if(pending||busy){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',listener);return()=>window.removeEventListener('beforeunload',listener);},[pending,busy]);
  useEffect(()=>{if(!selection||!floor)return;const list=selection.kind==='node'?floor.nodes:selection.kind==='wall'?floor.walls:selection.kind==='opening'?floor.openings:selection.kind==='room'?floor.rooms:floor.areas??[];if(!list.some(item=>item.id===selection.objectID))setSelection(null);},[current?.revision,floor?.id]);
  useEffect(()=>{const keyboard=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null;if(!target?.closest('.spatial-workspace')||target.closest('input,textarea,select,[contenteditable=true]')||!(event.metaKey||event.ctrlKey)||disabled)return;const key=event.key.toLowerCase();if(key==='z'){event.preventDefault();void history(event.shiftKey?'redo':'undo');}else if(key==='y'){event.preventDefault();void history('redo');}};window.addEventListener('keydown',keyboard);return()=>window.removeEventListener('keydown',keyboard);},[stored,disabled]);
  async function refreshLibrary() {const gen=generation.current,store=storeRef.current;try{await access();const entries=await store?.list();await access();if(entries&&gen===generation.current&&store===storeRef.current)setLibrary(entries);}catch(cause){if(gen===generation.current)setError(errorText(cause));}}
  async function guardScope(gen:number){if(gen!==generation.current)throw new Error('Workspace context changed. This operation was cancelled.');await access();if(gen!==generation.current)throw new Error('Workspace context changed. This operation was cancelled.');}
  function showWorkspace(value:StoredWorkspace){setStored(value);setPending(null);setFloorID(value.document.floors[0].id);setSelection(null);setFrozen(null);setMode('plan');setTool('select');setNotice('');setMobilePanel('canvas');}
  async function create(document:SpatialDocument){const value=await run(async store=>{const created=await store.create(document);await refreshLibrary();return created;});if(value){showWorkspace(value);setModal(null);}}
  async function open(documentID:string){if(pending&&!confirm('Discard the unsaved correction and open another layout? Your last saved revision remains available.'))return;const value=await run(store=>store.open(documentID));if(value)showWorkspace(value);}
  async function commitEdit(commands:EditCommand[], retry=false):Promise<boolean>{if(!stored||busyRef.current||(!retry&&pending))return false;let preview:SpatialDocument;const expected=retry&&pending?pending.expected:stored.document.revision;try{preview=retry&&pending?pending.preview:applyCommands(stored.document,commands,expected).document;}catch(cause){setError(errorText(cause));return false;}setPending({expected,commands,preview});const value=await run(store=>store.apply(stored.document.documentID,expected,commands));if(value){setStored(value);setPending(null);setNotice('Correction saved on this device.');await refreshLibrary();return true;}return false;}
  async function history(action:'undo'|'redo'){if(!stored||disabled)return;const value=await run(store=>store[action](stored.document.documentID,stored.document.revision));if(value){setStored(value);setNotice(action==='undo'?'Previous geometry restored as a new saved revision.':'Correction reapplied as a new saved revision.');await refreshLibrary();}}
  async function imported(file:File){if(file.size>64*1024*1024){setError('This file exceeds the 64 MB import safety limit.');return;}const gen=generation.current;const value=await run(async store=>{const parsed=await importDocument(new Uint8Array(await file.arrayBuffer()),file.name);await guardScope(gen);const saved=await store.create(parsed);await refreshLibrary();return saved;});if(value){showWorkspace(value);setNotice('Validated document imported and saved. Original Apple captures are not reconstructed from this file.');}}
  async function capture(){const gen=generation.current;const value=await run(async store=>{const document=await captureRoom();await guardScope(gen);const saved=await store.create(document);await refreshLibrary();return saved;});if(value){showWorkspace(value);setNotice('Captured geometry saved. Original Apple capture remains in protected native storage.');setModal(null);}}
  async function prepareExport(){if(!stored||disabled)return;const value=await run(store=>store.freeze(stored.document.documentID,stored.document.revision));if(value){setFrozen(value);setExportFloorID(value.document.floors.some(f=>f.id===floorID)?floorID:value.document.floors[0].id);setModal('export');}}
  async function download(){if(!frozen)return;const gen=generation.current;const result=await run(async()=>{const selected=formats.find(format=>format.id===exportFormat)!;const target=selected.scope==='floor'||(exportFormat==='pdf'&&exportScope==='floor')?exportFloorID:undefined;const artifact=await exportRevision(frozen,exportFormat,target);await guardScope(gen);const delivery=await saveExport(artifact);return{artifact,delivery};});if(result)setNotice(result.delivery.completed?`Revision ${result.artifact.revision} prepared for ${capability.available?'sharing':'download'}.`:'Export sharing was cancelled. The saved revision is unchanged.');}
  async function showRevisions(){if(!stored||disabled)return;const value=await run(store=>store.revisions(stored.document.documentID));if(value){setRevisions(value);setModal('revisions');}}
  const select=(value:Selection|null)=>{setSelection(value);};
  const allObjects:Selection[]=floor?[...floor.rooms.map(r=>({floorID:floor.id,kind:'room' as const,objectID:r.id})),...(floor.areas??[]).map(a=>({floorID:floor.id,kind:'area' as const,objectID:a.id})),...floor.walls.map(w=>({floorID:floor.id,kind:'wall' as const,objectID:w.id})),...floor.openings.map(o=>({floorID:floor.id,kind:'opening' as const,objectID:o.id})),...floor.nodes.map(n=>({floorID:floor.id,kind:'node' as const,objectID:n.id}))]:[];
  return <div className="spatial-workspace" data-mode={context.mode}>
    <header className="spatial-header"><button className="spatial-brand" onClick={()=>{if(pending){setError('Save or discard the pending correction before closing this layout.');return;}setStored(null);setSelection(null);setError('');}} aria-label="Auxilium Spatial saved layouts"><Mark/><span>auxilium<span className="spatial-brand-divider"/>spatial</span></button><div className="spatial-environment">{context.mode==='auxiliumos'?<><span className="spatial-dot"/> {context.projectLabel}</>:context.mode==='auxiliumos-personal'?<><span className="spatial-dot"/> AuxiliumOS · Personal synthetic workspace</>:<><span className="spatial-dot"/> Private on this device</>}</div><button className="spatial-capture-button" disabled={busy||!!pending||accessDenied} onClick={()=>capability.available?void capture():setModal('capture')}><span>{capability.available?'Capture rooms':'iPhone capture'}</span></button></header>
    <input ref={importInput} type="file" accept=".json,.zip,.auxilium,.spatial" className="spatial-hidden-input" onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void imported(file);}} />
    {(error||pending&&!busy||notice) && <div className={`spatial-message ${error?'spatial-message-error':''}`} role={error?'alert':'status'}><div>{error||notice}{pending&&!busy&&<strong> Your correction is visible but has not been saved.</strong>}</div><div>{pending&&!busy&&<><button onClick={()=>void commitEdit(pending.commands,true)}>Retry save</button><button onClick={()=>{setPending(null);setError('');setNotice('Returned to the saved revision.');}}>Discard unsaved edit</button><button onClick={()=>{if(stored)void run(store=>store.open(stored.document.documentID)).then(value=>{if(value){showWorkspace(value);setNotice('Opened the latest saved draft. The unsaved correction was discarded.');}});}}>Reopen latest saved</button></>}{!pending&&<button aria-label="Dismiss message" onClick={()=>{setError('');setNotice('');}}>×</button>}</div></div>}
    {accessDenied?<main className="spatial-access-blocked"><h1>Workspace access is unavailable</h1><p>This workspace has closed its authorized view. Return to the host application to re-establish your context.</p></main>:!current?<main className="spatial-library"><div className="spatial-library-heading"><div><div className="spatial-eyebrow">YOUR SPATIAL WORKSPACE</div><h1>A clear picture of<br/>every room.</h1><p>Capture, correct and explore a layout.<br/>Keep one geometry from the first scan to the saved drawing.</p></div><div className="spatial-library-actions"><button className="spatial-primary" disabled={busy||loading} onClick={()=>setModal('new')}>+ New layout</button><button disabled={busy||loading} onClick={()=>importInput.current?.click()}>Import a layout</button></div></div><div className="spatial-library-list"><div className="spatial-section-title"><h2>Saved layouts</h2><span>{loading?'Opening local storage…':'Saved in this browser or installed app'}</span></div>{library.length?<div className="spatial-project-grid">{library.map(item=><button className="spatial-project-card" key={item.documentID} disabled={busy} onClick={()=>void open(item.documentID)}><div className="spatial-project-icon"><Mark/></div><h3>{item.title}</h3><p>Revision {item.revision}<span>·</span>{new Date(item.updatedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</p><span className="spatial-card-arrow">↗</span></button>)}</div>:!loading&&<div className="spatial-empty-library"><div className="spatial-empty-symbol">⌑</div><div><h3>Your layouts will be saved here.</h3><p>Start with a new drawing, import a validated document, or explore the synthetic example.</p></div></div>}</div><div className="spatial-example-card"><div className="spatial-example-diagram" aria-hidden="true"><svg viewBox="0 0 160 90"><path d="M20 15H140V75H20Z M80 15V38 M80 53V75" fill="#e9f2f7" stroke="#416276" strokeWidth="2"/><path d="M40 75H60" stroke="#9cbed1" strokeWidth="4"/><path d="M80 38Q65 38 65 53H80" fill="none" stroke="#7198ae"/></svg></div><div><div className="spatial-eyebrow">A PLACE TO TRY THINGS</div><h3>Explore a two-room example</h3><p>Move a wall, adjust a door, then walk between rooms. Synthetic data only.</p></div><button disabled={busy||loading} onClick={()=>void create(syntheticDocument())}>Open example ↗</button></div><p className="spatial-library-footnote">Local-first storage · No live publication · Unverified geometry</p></main>:floor&&<>
      <div className="spatial-document-heading"><div><button className="spatial-back" aria-label="Back to saved layouts" disabled={!!pending||busy} onClick={()=>setStored(null)}>←</button><div><h1>{current.title}</h1><div className="spatial-save-state"><span className={`spatial-dot ${pending?'spatial-dot-amber':''}`}/>{busy?'Working…':pending?'Unsaved correction':'Saved locally'}<span>·</span>Revision {current.revision}{current.title.toLowerCase().includes('synthetic')&&<span className="spatial-synthetic-badge">SYNTHETIC</span>}</div></div></div><div className="spatial-document-actions"><button disabled={disabled||!stored?.canUndo} onClick={()=>void history('undo')} title="Undo last correction">↶ <span>Undo</span></button><button disabled={disabled||!stored?.canRedo} onClick={()=>void history('redo')} title="Redo last correction">↷ <span>Redo</span></button><button disabled={disabled} onClick={()=>setModal('review')}>Review{issues.length?` (${issues.length})`:''}</button><button disabled={disabled} onClick={()=>void showRevisions()}>Revisions</button><button className="spatial-primary" disabled={disabled} onClick={()=>void prepareExport()}>Export ↗</button></div></div>
      <div className="spatial-editor" data-mobile-panel={mobilePanel}><aside className="spatial-object-panel"><div className="spatial-floor-picker"><label>FLOOR<select value={floor.id} disabled={disabled} onChange={event=>{setFloorID(event.target.value);setSelection(null);setTool('select');}}>{current.floors.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label><button aria-label="Manage floors" disabled={disabled} onClick={()=>setModal('floor')}>⋯</button></div><div className="spatial-object-heading"><h2>Objects</h2><button disabled={disabled} onClick={()=>{setBoundaryRoom(undefined);setModal('room');}} title="Create room from boundary walls">+ Room</button></div><div className="spatial-object-list" aria-label="Layout objects">{allObjects.length?(['room','area','wall','opening','node'] as const).map(kind=><div className="spatial-object-group" key={kind}>{allObjects.some(s=>s.kind===kind)&&<h3>{kind==='node'?'Corners':kind==='opening'?'Doors & openings':`${kind[0].toUpperCase()}${kind.slice(1)}s`}</h3>}{allObjects.filter(s=>s.kind===kind).map(item=><button key={item.objectID} aria-pressed={selection?.objectID===item.objectID&&selection.kind===item.kind} onClick={()=>select(item)}><span className={`spatial-object-symbol spatial-symbol-${kind}`}>{kind==='room'?'▱':kind==='wall'?'╱':kind==='node'?'·':kind==='area'?'▧':'⌑'}</span><span>{objectLabel(floor,item)}</span>{kind==='wall'&&floor.walls.find(w=>w.id===item.objectID)?.provenance.origin==='inferred'&&<span className="spatial-inferred-mark" title="Inferred boundary">!</span>}</button>)}</div>):<p className="spatial-object-empty">Start by drawing walls in the plan. Connect shared corners, then create a room from its boundary.</p>}</div><div className="spatial-review-note"><span>◌</span><div><strong>{current.reviewState==='needsReview'?'Review needed':'Reviewed geometry'}</strong><p>{floor.walls.some(w=>w.provenance.origin==='inferred')?'Dashed walls are inferred. Check incomplete boundaries.':'Check room connections and openings against the property.'}</p></div></div></aside>
        <main className="spatial-canvas-column"><div className="spatial-canvas-toolbar"><div className="spatial-segmented"><button aria-pressed={mode==='plan'} onClick={()=>setMode('plan')}>2D plan</button><button aria-pressed={mode==='model'} onClick={()=>setMode('model')}>3D model</button></div>{mode==='plan'&&<div className="spatial-tools" aria-label="Drawing tools"><button aria-label="Select objects" aria-pressed={tool==='select'} onClick={()=>setTool('select')} disabled={disabled}>↖ <span>Select</span></button><button aria-label="Pan plan" aria-pressed={tool==='pan'} onClick={()=>setTool('pan')} disabled={disabled}>✥ <span>Pan</span></button><button aria-label="Draw wall" aria-pressed={tool==='wall'} onClick={()=>setTool('wall')} disabled={disabled}>╱ <span>Wall</span></button><button aria-label="Draw area" aria-pressed={tool==='area'} onClick={()=>setTool('area')} disabled={disabled}>▧ <span>Area</span></button></div>}<span className="spatial-view-label">{floor.label}</span></div>{mode==='plan'?<FloorplanCanvas floor={floor} selection={selection} onSelect={select} onEdit={commands=>void commitEdit(commands)} disabled={disabled} tool={tool} onTool={setTool} onError={setError}/>:<ModelViewport document={current} floor={floor} selection={selection} onSelect={select}/>}<div className="spatial-canvas-footer"><span>{mode==='plan'?'PLAN VIEW':'GEOMETRIC MODEL'}</span><span>Unverified geometry · No measurement claims</span></div></main>
        <Inspector floor={floor} selection={selection} onSelect={select} onEdit={commands=>void commitEdit(commands)} disabled={disabled} onBoundary={roomID=>{setBoundaryRoom(roomID);setModal('room');}}/>
      </div><nav className="spatial-mobile-tabs" aria-label="Workspace panels"><button aria-pressed={mobilePanel==='objects'} onClick={()=>setMobilePanel('objects')}>Objects</button><button aria-pressed={mobilePanel==='canvas'} onClick={()=>setMobilePanel('canvas')}>Layout</button><button aria-pressed={mobilePanel==='details'} onClick={()=>setMobilePanel('details')}>Details</button></nav>
    </>}
    {modal==='review'&&floor&&<Dialog error={error} title="Review this floor" onClose={()=>setModal(null)}><p>These checks describe the current geometry. Check the drawing against the property; they do not certify a scan or its measurements.</p>{issues.length?<div className="spatial-review-list">{issues.slice(0,200).map(issue=><button key={issue.id} onClick={()=>{setMode('plan');setModal(null);setTool('select');if(issue.selection){setSelection(issue.selection);setMobilePanel('details');}else{setBoundaryRoom(undefined);setModal('room');}}}><span className="spatial-eyebrow">{issue.severity}</span><strong>{issue.title}</strong><span>{issue.detail}</span><small>{issue.selection?objectLabel(floor,issue.selection):'Create a room'} →</small></button>)}{issues.length>200&&<p>Showing the first 200 checks. Correct these and reopen Review to continue.</p>}</div>:<p>No structural issues were found by these limited checks. Visual inspection and property verification are still required.</p>}</Dialog>}
    {modal==='new'&&<Dialog error={error} title="New layout" onClose={()=>setModal(null)}><NewLayoutForm disabled={busy} onCreate={title=>void create(freshDocument(title))}/></Dialog>}
    {modal==='room'&&floor&&<Dialog error={error} title={boundaryRoom?'Edit room boundary':'Create room'} onClose={()=>setModal(null)}><BoundaryForm floor={floor} roomID={boundaryRoom} onSave={commands=>void commitEdit(commands).then(ok=>{if(ok)setModal(null);})}/></Dialog>}
    {modal==='floor'&&current&&floor&&<Dialog error={error} title="Manage floors" onClose={()=>setModal(null)}><FloorForm floor={floor} floors={current.floors} disabled={disabled} onEdit={commands=>void commitEdit(commands).then(ok=>{if(ok)setModal(null);})}/></Dialog>}
    {modal==='capture'&&<Dialog error={error} title="Apple room capture" onClose={()=>setModal(null)}><div className="spatial-capture-info"><Mark/><h3>Capture with the installed iPhone app</h3><p>{capability.reason||'RoomPlan and LiDAR capture are available through the installed app on a supported iPhone Pro.'}</p><p>This browser workspace edits the same validated geometry. It does not access LiDAR or imitate a native scan.</p><p>Connected-room capture retains completed rooms and stops when alignment cannot be verified.</p></div></Dialog>}
    {modal==='export'&&frozen&&<Dialog error={error} title="Export a saved revision" onClose={()=>setModal(null)}><p>Every file below comes from <strong>revision {frozen.document.revision}</strong> of {frozen.document.title}. Later edits cannot change this saved snapshot.</p><label>Format<select value={exportFormat} onChange={event=>setExportFormat(event.target.value as ExportFormat)}>{formats.map(format=><option key={format.id} value={format.id} disabled={format.scope==='one'&&frozen.document.floors.length>1}>{format.label}{format.scope==='one'&&frozen.document.floors.length>1?' (single floor only)':''}</option>)}</select></label><p className="spatial-caption">{formats.find(format=>format.id===exportFormat)?.description}</p>{exportFormat==='pdf'&&<label>Pages<select value={exportScope} onChange={event=>setExportScope(event.target.value as 'all'|'floor')}><option value="all">Every floor</option><option value="floor">Selected floor only</option></select></label>}{(formats.find(format=>format.id===exportFormat)?.scope==='floor'||exportFormat==='pdf'&&exportScope==='floor')&&<label>Floor in this revision<select value={exportFloorID} onChange={event=>setExportFloorID(event.target.value)}>{frozen.document.floors.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label>}<div className="spatial-export-identity"><span>Exact content identity</span><code>{frozen.hash}</code></div><p className="spatial-caption">Raw native captures remain separately protected. Exporting this layout is your explicit choice; no remote publication is enabled.</p><button className="spatial-primary spatial-full-button" disabled={busy} onClick={()=>void download()}>{busy?'Preparing…':capability.available?'Prepare and share':'Prepare download'}</button>{notice&&<p role="status">{notice}</p>}</Dialog>}
    {modal==='revisions'&&stored&&<Dialog error={error} title="Saved revisions" onClose={()=>setModal(null)}><p>Editing saves the current draft. Freeze a revision to keep an immutable export source.</p><button className="spatial-primary spatial-full-button" disabled={disabled} onClick={()=>void run(async store=>{await store.freeze(stored.document.documentID,stored.document.revision);return store.revisions(stored.document.documentID);}).then(value=>{if(value)setRevisions(value);})}>Freeze revision {stored.document.revision}</button>{revisions.length?<div className="spatial-revision-list">{revisions.map(revision=><div key={revision.document.revision}><button onClick={()=>{setFrozen(revision);setExportFloorID(revision.document.floors.some(f=>f.id===floorID)?floorID:revision.document.floors[0].id);setModal('export');}}><strong>Revision {revision.document.revision}</strong><span>{new Date(revision.createdAt).toLocaleString()}</span><small>{revision.hash.slice(0,16)}… · Export this version ↗</small></button>{revision.document.revision!==stored.document.revision&&<button disabled={disabled} onClick={()=>{if(confirm(`Restore geometry from revision ${revision.document.revision}? This creates a new draft revision and preserves the frozen source and undo history.`))void run(store=>store.restore(stored.document.documentID,revision.document.revision,stored.document.revision)).then(value=>{if(value){setStored(value);setNotice(`Geometry restored from revision ${revision.document.revision} as new revision ${value.document.revision}.`);setModal(null);void refreshLibrary();}});}}>Restore as new revision</button>}</div>)}</div>:<p>No frozen revisions yet. Your current draft is saved locally.</p>}</Dialog>}
  </div>;
}
function NewLayoutForm({disabled,onCreate}:{disabled:boolean;onCreate:(title:string)=>void}){const[title,setTitle]=useState('');return <form onSubmit={event=>{event.preventDefault();if(title.trim())onCreate(title);}}><label>Layout name<input autoFocus value={title} maxLength={256} placeholder="e.g. Riverside ground floor" onChange={event=>setTitle(event.target.value)}/></label><p>Start with a blank floor. Draw connected walls, label rooms, and correct the same geometry in every view.</p><button className="spatial-primary spatial-full-button" type="submit" disabled={disabled||!title.trim()}>Create layout</button></form>;}
function FloorForm({floor,floors,disabled,onEdit}:{floor:Floor;floors:Floor[];disabled:boolean;onEdit:(commands:EditCommand[])=>void}){const[label,setLabel]=useState(floor.label),[elevation,setElevation]=useState(String(floor.elevation)),[newLabel,setNewLabel]=useState('');return <><form onSubmit={event=>{event.preventDefault();onEdit([{type:'updateFloor',floorID:floor.id,label,elevation:Number(elevation)}]);}}><label>Current floor name<input value={label} maxLength={256} onChange={event=>setLabel(event.target.value)}/></label><label>Model elevation<input type="number" value={elevation} step="0.05" min="-10000" max="10000" onChange={event=>setElevation(event.target.value)}/></label><p className="spatial-caption">A model coordinate, not a verified building measurement. Floors remain separate until explicit geometry describes a connection.</p><button className="spatial-full-button" disabled={disabled||!label.trim()||!elevation.trim()||!Number.isFinite(Number(elevation))}>Save floor</button></form><hr/><form onSubmit={event=>{event.preventDefault();onEdit([{type:'addFloor',floor:{id:uid(),label:newLabel.trim(),elevation:floor.elevation+3,nodes:[],walls:[],openings:[],rooms:[]}}]);}}><label>New floor name<input value={newLabel} maxLength={256} onChange={event=>setNewLabel(event.target.value)}/></label><button className="spatial-full-button" disabled={disabled||!newLabel.trim()} type="submit">+ Add empty floor</button></form><hr/><button className="spatial-danger spatial-full-button" disabled={disabled||floors.length<=1} onClick={()=>{if(confirm(`Delete ${floor.label} and its geometry from the draft? Undo can restore it. Frozen revisions remain unchanged.`))onEdit([{type:'deleteFloor',floorID:floor.id}]);}}>Delete current floor</button></>;}
