begin;

-- INTAKE-001A. Synthetic development only: no PHI, approved scope, scientific
-- conclusion, agreement, project conversion, scheduling or mobilization path.
-- Filename generated by the integration lead with `supabase migration new`.
alter table public.account_capability_grants
  drop constraint account_capability_grants_scope_allowed,
  add constraint account_capability_grants_scope_allowed check (
    (capability_key = 'view_account' and scope_kind = 'account' and facility_id is null)
    or (capability_key = 'view_asset' and scope_kind = 'facility' and facility_id is not null)
    or (capability_key = 'view_asset' and scope_kind = 'all_facilities' and facility_id is null)
    or (capability_key in ('ingest_private_object', 'submit_request', 'triage_request')
      and scope_kind = 'facility' and facility_id is not null)
  );

create table public.incidents (
  id uuid primary key default pg_catalog.gen_random_uuid(),
  account_id uuid not null references public.client_accounts (id),
  facility_id uuid not null,
  title text not null check (char_length(title) between 1 and 160 and char_length(btrim(title)) > 0),
  occurred_at timestamptz,
  created_by_profile_id uuid not null references public.user_profiles (id),
  created_by_auth_user_id uuid not null,
  created_at timestamptz not null default pg_catalog.clock_timestamp(),
  is_demo boolean not null default true check (is_demo),
  unique (id, account_id, facility_id),
  foreign key (facility_id, account_id) references public.facilities (id, account_id)
);

create table public.project_requests (
  id uuid primary key default pg_catalog.gen_random_uuid(),
  account_id uuid not null references public.client_accounts (id),
  facility_id uuid,
  incident_id uuid,
  legacy_incident_request_id uuid unique,
  submitted_by_profile_id uuid references public.user_profiles (id),
  submitted_by_auth_user_id uuid,
  idempotency_key uuid,
  original_submission jsonb not null check (jsonb_typeof(original_submission) = 'object'),
  title text not null,
  original_wording text not null,
  original_issue_id text,
  original_intent_id text,
  catalogue_version text not null,
  urgency text not null check (urgency in ('routine', 'urgent', 'emergency')),
  classified_issue_id text,
  classified_intent_id text,
  assigned_to_profile_id uuid references public.user_profiles (id),
  next_action text check (next_action is null or char_length(next_action) <= 2000),
  status text not null,
  revision bigint not null default 1 check (revision > 0),
  created_at timestamptz not null default pg_catalog.clock_timestamp(),
  updated_at timestamptz not null default pg_catalog.clock_timestamp(),
  is_demo boolean not null default true,
  unique (id, account_id),
  unique (id, account_id, facility_id),
  unique (account_id, submitted_by_profile_id, idempotency_key),
  foreign key (facility_id, account_id) references public.facilities (id, account_id),
  foreign key (incident_id, account_id, facility_id)
    references public.incidents (id, account_id, facility_id),
  foreign key (legacy_incident_request_id, account_id)
    references public.incident_requests (id, account_id),
  foreign key (account_id, assigned_to_profile_id)
    references public.account_access (account_id, user_profile_id),
  constraint project_requests_original_shape check (
    (legacy_incident_request_id is not null and legacy_incident_request_id = id and idempotency_key is null
      and catalogue_version = 'legacy-unversioned')
    or (legacy_incident_request_id is null and facility_id is not null
      and submitted_by_profile_id is not null and submitted_by_auth_user_id is not null
      and idempotency_key is not null and is_demo
      and char_length(btrim(title)) between 1 and 160
      and char_length(btrim(original_wording)) between 1 and 8000
      and original_issue_id ~ '^ISSUE-(00[1-9]|01[0-9])$'
      and original_issue_id is not null
      and original_intent_id ~ '^INTENT-(00[1-9]|01[0-6])$'
      and original_intent_id is not null and catalogue_version = '2026-10-08.1')
  ),
  constraint project_requests_current_classification check (
    (classified_issue_id is null or classified_issue_id ~ '^ISSUE-(00[1-9]|01[0-9])$')
    and (classified_intent_id is null or classified_intent_id ~ '^INTENT-(00[1-9]|01[0-6])$')
  ),
  constraint project_requests_current_status check (
    legacy_incident_request_id is not null or status in (
      'submitted', 'intake_completeness_review', 'needs_client_information',
      'classification_review', 'technical_review', 'safety_review',
      'revision_proposed', 'client_revision_pending', 'declined', 'cancelled')),
  constraint project_requests_information_owner check (
    legacy_incident_request_id is not null or status <> 'needs_client_information'
    or (assigned_to_profile_id is not null and char_length(btrim(next_action)) > 0
      and next_action is not null))
);
create index project_requests_account_page_idx on public.project_requests (account_id, id);
create index project_requests_account_status_page_idx on public.project_requests (account_id, status, id);
create index project_requests_facility_idx on public.project_requests (facility_id, account_id);
create index project_requests_submitter_idx on public.project_requests (submitted_by_profile_id, account_id);
create index project_requests_assignee_idx on public.project_requests (assigned_to_profile_id);
create index project_requests_incident_idx on public.project_requests (incident_id, account_id, facility_id);
create index incidents_facility_idx on public.incidents (facility_id, account_id);
create index incidents_creator_idx on public.incidents (created_by_profile_id);

-- Preserve unknown legacy facts as unknown. The title is the sole source text;
-- no incident, original classification, human approval or Auth actor is invented.
create function private.request_from_legacy(p_legacy public.incident_requests)
returns public.project_requests language plpgsql stable security invoker set search_path = '' as $$
declare result public.project_requests%rowtype;
begin
  result.id := p_legacy.id; result.account_id := p_legacy.account_id;
  result.facility_id := p_legacy.facility_id; result.legacy_incident_request_id := p_legacy.id;
  result.submitted_by_profile_id := p_legacy.submitted_by_profile_id;
  result.original_submission := jsonb_build_object('legacy_incident_request', to_jsonb(p_legacy));
  result.title := p_legacy.title; result.original_wording := p_legacy.title;
  result.catalogue_version := 'legacy-unversioned'; result.urgency := 'routine';
  -- routine is wire compatibility only: the legacy source recorded no urgency.
  -- The legacy-unversioned UI must display that fact as "Not recorded".
  result.status := p_legacy.request_status; result.revision := 1;
  result.created_at := p_legacy.created_at; result.updated_at := p_legacy.updated_at;
  result.is_demo := p_legacy.is_demo;
  return result;
end;
$$;
insert into public.project_requests select (private.request_from_legacy(legacy)).*
  from public.incident_requests as legacy;

-- The unchanged canonical seed also supports fresh migrations -> seed. This
-- narrow bootstrap exception is not a runtime legacy writer or import API.
-- Neither a service key, switched application role, nor forged JWT can enter it.
create function private.intake_seed_context()
returns boolean language sql stable security invoker set search_path = '' as $$
  select session_user in ('postgres', 'supabase_admin')
    and coalesce(nullif(pg_catalog.current_setting('role', true), 'none'), session_user::text)
      = session_user::text
$$;
create function private.is_canonical_intake_seed(p_legacy public.incident_requests)
returns boolean language sql immutable security invoker set search_path = '' as $$
  select coalesce(p_legacy.id = '00000000-0000-4000-8000-000000000401'::uuid
    and p_legacy.account_id = '00000000-0000-4000-8000-000000000001'::uuid
    and p_legacy.facility_id = '00000000-0000-4000-8000-000000000301'::uuid
    and p_legacy.submitted_by_profile_id = '00000000-0000-4000-8000-000000000105'::uuid
    and p_legacy.title = 'Water Intrusion Demo' and p_legacy.request_status = 'draft'
    and p_legacy.is_demo, false)
$$;

alter table public.documents add column project_request_id uuid,
  add constraint documents_project_request_account_fk
    foreign key (project_request_id, account_id) references public.project_requests (id, account_id);
update public.documents set project_request_id = incident_request_id where incident_request_id is not null;
create index documents_project_request_idx on public.documents (project_request_id, account_id);

create table public.request_responses (
  id uuid primary key default pg_catalog.gen_random_uuid(),
  request_id uuid not null,
  account_id uuid not null,
  facility_id uuid not null,
  submitted_by_profile_id uuid not null references public.user_profiles (id),
  submitted_by_auth_user_id uuid not null,
  body text not null check (char_length(body) between 1 and 8000 and char_length(btrim(body)) > 0),
  request_revision bigint not null check (request_revision > 1),
  created_at timestamptz not null default pg_catalog.clock_timestamp(),
  is_demo boolean not null default true check (is_demo),
  unique (request_id, request_revision),
  foreign key (request_id, account_id, facility_id)
    references public.project_requests (id, account_id, facility_id)
);
create index request_responses_request_idx on public.request_responses (request_id, created_at, id);
create index request_responses_submitter_idx on public.request_responses (submitted_by_profile_id);

alter table public.incidents enable row level security;
alter table public.project_requests enable row level security;
alter table public.request_responses enable row level security;
-- The sole client read/write surface is the checked RPC set below. There are
-- no permissive table policies; a future ACL mistake still encounters RLS.
revoke all on public.incidents, public.project_requests, public.request_responses
  from public, anon, authenticated, service_role;
grant select on public.incidents, public.project_requests, public.request_responses to service_role;

alter table public.audit_events
  drop constraint audit_events_access_event_scope_check,
  add constraint audit_events_access_event_scope_check check (
    (actor_kind = 'legacy_fixture' and account_id is not null)
    or (actor_kind in ('user', 'system') and object_id is not null and is_internal_only and (
      (account_id is null and object_type = 'user_profile'
        and event_type in ('profile_created', 'profile_updated', 'profile_deleted'))
      or (account_id is not null and object_type = 'account_access'
        and event_type in ('account_access_created', 'account_access_updated', 'account_access_deleted'))
      or (account_id is not null and object_type = 'account_capability_grant'
        and event_type in ('capability_grant_created', 'capability_grant_updated',
          'capability_grant_revoked', 'capability_grant_restored', 'capability_grant_deleted'))
      or (account_id is not null and object_type = 'private_object'
        and event_type = 'private_object_reserved' and actor_kind = 'user' and is_demo)
      or (account_id is null and object_type = 'private_object_reservation_config'
        and event_type in ('private_object_reservation_config_created',
          'private_object_reservation_config_updated') and actor_kind = 'system' and is_demo)
      or (account_id is not null and actor_kind = 'user' and is_demo and (
        (object_type = 'incident' and event_type = 'incident_created')
        or (object_type = 'project_request' and event_type in ('request_created',
          'request_submitted', 'request_assigned', 'request_reclassified', 'request_status_changed'))
        or (object_type = 'request_response' and event_type = 'missing_information_received')))
    ))
  );

create function private.intake_authenticated_subject()
returns uuid language plpgsql security invoker set search_path = '' as $$
declare subject_id uuid; claims jsonb;
begin
  if session_user <> 'authenticator'
    or pg_catalog.current_setting('role', true) is distinct from 'authenticated' then
    raise exception 'Intake unavailable' using errcode = '42501';
  end if;
  begin
    subject_id := auth.uid(); claims := auth.jwt();
    if subject_id is null or jsonb_typeof(claims) is distinct from 'object'
      or claims ->> 'role' is distinct from 'authenticated'
      or claims -> 'is_anonymous' is distinct from 'false'::jsonb
      or (claims ->> 'sub')::uuid is distinct from subject_id then
      raise exception 'Intake unavailable' using errcode = '42501';
    end if;
  exception when invalid_text_representation then
    raise exception 'Intake unavailable' using errcode = '42501';
  end;
  if private.current_subject_id() is null then
    raise exception 'Intake unavailable' using errcode = '42501';
  end if;
  return subject_id;
end;
$$;

-- Internal profile argument permits same-facility assignee validation only.
-- Never executable by clients; it is not a directory-wide entitlement oracle.
create function private.intake_profile_access(p_profile uuid, p_account uuid, p_facility uuid, p_capability text)
returns boolean language sql stable security invoker set search_path = '' as $$
  select exists (
    select 1 from public.user_profiles p
    join public.account_access a on a.user_profile_id = p.id
    join public.client_accounts c on c.id = a.account_id
    join public.facilities f on f.account_id = c.id and f.id = p_facility
    where p.id = p_profile and p.auth_user_id is not null and p.identity_status = 'active'
      and p.is_demo and a.account_id = p_account and a.membership_status = 'active'
      and a.is_demo and c.is_demo and f.is_demo
      and exists (select 1 from public.account_capability_grants g where g.account_id = p_account
        and g.user_profile_id = p_profile and g.capability_key = 'view_account'
        and g.scope_kind = 'account' and g.facility_id is null and g.revoked_at is null and g.is_demo)
      and exists (select 1 from public.account_capability_grants g where g.account_id = p_account
        and g.user_profile_id = p_profile and g.capability_key = 'view_asset'
        and ((g.scope_kind = 'facility' and g.facility_id = p_facility)
          or (g.scope_kind = 'all_facilities' and g.facility_id is null))
        and g.revoked_at is null and g.is_demo)
      and (p_capability is null or (p_capability in ('submit_request', 'triage_request')
        and exists (select 1 from public.account_capability_grants g where g.account_id = p_account
          and g.user_profile_id = p_profile and g.capability_key = p_capability
          and g.scope_kind = 'facility' and g.facility_id = p_facility
          and g.revoked_at is null and g.is_demo)))
  )
$$;

create function private.lock_intake_profile(p_profile uuid, p_account uuid, p_facility uuid, p_capability text)
returns boolean language plpgsql security invoker set search_path = '' as $$
declare candidate record; has_account boolean := false; has_asset boolean := false;
  has_action boolean := p_capability is null;
begin
  -- SHARE locks, not KEY SHARE: status/demo/revocation changes conflict until
  -- commit. Recheck predicates after waiting; higher isolation may abort.
  -- All mutation callers use profile, account, membership, facility, UUID grants
  -- then request row order. Assignees use the same order; no grants are inferred.
  perform 1 from public.user_profiles where id = p_profile and auth_user_id is not null
    and identity_status = 'active' and is_demo for share;
  if not found then return false; end if;
  perform 1 from public.client_accounts where id = p_account and is_demo for share;
  if not found then return false; end if;
  perform 1 from public.account_access where account_id = p_account and user_profile_id = p_profile
    and membership_status = 'active' and is_demo for share;
  if not found then return false; end if;
  perform 1 from public.facilities where id = p_facility and account_id = p_account and is_demo for share;
  if not found then return false; end if;
  for candidate in
    select capability_key from public.account_capability_grants
    where account_id = p_account and user_profile_id = p_profile and revoked_at is null and is_demo and (
      (capability_key = 'view_account' and scope_kind = 'account' and facility_id is null)
      or (capability_key = 'view_asset' and ((scope_kind = 'facility' and facility_id = p_facility)
        or (scope_kind = 'all_facilities' and facility_id is null)))
      or (capability_key = p_capability and p_capability in ('submit_request', 'triage_request')
        and scope_kind = 'facility' and facility_id = p_facility))
    order by id for share
  loop
    if candidate.capability_key = 'view_account' then has_account := true;
    elsif candidate.capability_key = 'view_asset' then has_asset := true;
    elsif candidate.capability_key = p_capability then has_action := true; end if;
  end loop;
  -- Only grants selected AND locked above may authorize the operation. Do not
  -- run a fresh broad predicate which could adopt a concurrently inserted but
  -- unlocked grant between this lock query and the business write.
  return has_account and has_asset and has_action;
end;
$$;

create function private.intake_transition_allowed(p_before text, p_after text)
returns boolean language sql immutable security invoker set search_path = '' as $$
  select coalesce(case p_before
    when 'submitted' then p_after = 'intake_completeness_review'
    when 'intake_completeness_review' then p_after in ('needs_client_information', 'classification_review',
      'technical_review', 'safety_review', 'declined', 'cancelled')
    when 'needs_client_information' then p_after in ('intake_completeness_review', 'declined', 'cancelled')
    when 'classification_review' then p_after in ('technical_review', 'safety_review', 'revision_proposed', 'declined', 'cancelled')
    when 'technical_review' then p_after in ('needs_client_information', 'classification_review', 'revision_proposed', 'declined', 'cancelled')
    when 'safety_review' then p_after in ('needs_client_information', 'classification_review', 'revision_proposed', 'declined', 'cancelled')
    when 'revision_proposed' then p_after in ('client_revision_pending', 'needs_client_information', 'declined', 'cancelled')
    when 'client_revision_pending' then p_after in ('needs_client_information', 'classification_review', 'declined', 'cancelled')
    else false end, false)
$$;

create function private.guard_intake_history()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if tg_table_name = 'project_requests' and tg_op = 'UPDATE' then
    if (to_jsonb(new) - array['classified_issue_id', 'classified_intent_id', 'assigned_to_profile_id',
      'next_action', 'status', 'revision', 'updated_at']) is distinct from
      (to_jsonb(old) - array['classified_issue_id', 'classified_intent_id', 'assigned_to_profile_id',
      'next_action', 'status', 'revision', 'updated_at']) then
      raise exception 'Original request is immutable' using errcode = '42501';
    end if;
    if old.status not in ('submitted', 'intake_completeness_review', 'needs_client_information',
      'classification_review', 'technical_review', 'safety_review', 'revision_proposed', 'client_revision_pending')
      or (new.status <> old.status and not private.intake_transition_allowed(old.status, new.status))
      or new.revision <> old.revision + 1 then
      raise exception 'Invalid intake transition' using errcode = '22023';
    end if;
    new.updated_at := pg_catalog.clock_timestamp();
    return new;
  end if;
  -- Preserve idempotent replays of the unchanged seed, not a second writer.
  if tg_table_name = 'incident_requests' and tg_op = 'INSERT' then
    if private.intake_seed_context() then
      if exists (select 1 from public.incident_requests old_row where old_row.id = new.id
        and (to_jsonb(old_row) - array['created_at', 'updated_at']) =
          (to_jsonb(new) - array['created_at', 'updated_at'])) then return null; end if;
      if private.is_canonical_intake_seed(new) then return new; end if;
    end if;
  end if;
  raise exception 'Intake history is immutable' using errcode = '42501';
end;
$$;
create trigger project_requests_immutable before update or delete on public.project_requests
  for each row execute function private.guard_intake_history();
create trigger project_requests_no_truncate before truncate on public.project_requests
  for each statement execute function private.guard_intake_history();
create trigger incidents_immutable before update or delete on public.incidents
  for each row execute function private.guard_intake_history();
create trigger incidents_no_truncate before truncate on public.incidents
  for each statement execute function private.guard_intake_history();
create trigger request_responses_immutable before update or delete on public.request_responses
  for each row execute function private.guard_intake_history();
create trigger request_responses_no_truncate before truncate on public.request_responses
  for each statement execute function private.guard_intake_history();
create trigger incident_requests_writer_cutover before insert or update or delete on public.incident_requests
  for each row execute function private.guard_intake_history();
create trigger incident_requests_no_truncate before truncate on public.incident_requests
  for each statement execute function private.guard_intake_history();

create function private.import_canonical_intake_seed()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if not private.intake_seed_context() or not private.is_canonical_intake_seed(new) then
    raise exception 'Intake history is immutable' using errcode = '42501'; end if;
  -- Atomic same-ID mapping. Conflicting new-model IDs fail the entire seed
  -- transaction; do not overwrite, repair or invent historical source facts.
  insert into public.project_requests select (private.request_from_legacy(new)).*;
  return null;
end;
$$;
create trigger incident_requests_canonical_seed_mapping after insert on public.incident_requests
  for each row execute function private.import_canonical_intake_seed();

create function private.link_canonical_intake_seed_document()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  -- Only these two exact existing fixtures receive an omitted compatibility
  -- link. Other documents and future document/version workflows are untouched.
  if new.project_request_id is null
    and new.account_id = '00000000-0000-4000-8000-000000000001'::uuid
    and new.facility_id = '00000000-0000-4000-8000-000000000301'::uuid
    and new.incident_request_id = '00000000-0000-4000-8000-000000000401'::uuid
    and new.version_label = 'v1' and new.is_internal_only and new.is_demo and (
      (new.id = '00000000-0000-4000-8000-000000000501'::uuid
        and new.title = 'Document Placeholder 001' and new.document_class = 'internal_note'
        and new.release_state = 'internal_draft')
      or (new.id = '00000000-0000-4000-8000-000000000502'::uuid
        and new.title = 'Client Upload Placeholder' and new.document_class = 'client_upload'
        and new.release_state = 'uploaded_unclassified')) then
    if not private.intake_seed_context() then return new; end if;
    perform 1 from public.project_requests r where r.id = new.incident_request_id
      and r.legacy_incident_request_id = new.incident_request_id and r.account_id = new.account_id;
    if not found then raise exception 'Legacy intake mapping unavailable' using errcode = '42501'; end if;
    new.project_request_id := new.incident_request_id;
  end if;
  return new;
end;
$$;
create trigger documents_canonical_intake_seed_link before insert on public.documents
  for each row execute function private.link_canonical_intake_seed_document();
revoke insert, update, delete, truncate on public.incident_requests from service_role;
revoke insert (id, account_id, facility_id, submitted_by_profile_id, title, request_status,
  is_demo, created_at, updated_at), update (id, account_id, facility_id, submitted_by_profile_id,
  title, request_status, is_demo, created_at, updated_at) on public.incident_requests from service_role;

create function private.audit_intake_change()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  event_auth uuid; event_profile uuid;
  event_names text[]; event_name text; event_object text; metadata jsonb;
  event_correlation uuid := pg_catalog.gen_random_uuid();
begin
  if tg_table_schema <> 'public' or tg_when <> 'AFTER' or tg_level <> 'ROW' then
    raise exception 'Unsupported intake audit context' using errcode = '55000';
  end if;
  if tg_table_name = 'project_requests' and tg_op = 'INSERT' then
    if new.legacy_incident_request_id is not null and private.intake_seed_context()
      and exists (select 1 from public.incident_requests legacy
        where legacy.id = new.legacy_incident_request_id and private.is_canonical_intake_seed(legacy)
          and new is not distinct from private.request_from_legacy(legacy)) then
      -- Historical fixture import, exactly as in migration-time backfill. The
      -- unchanged seed supplies legacy_fixture provenance; never fabricate a
      -- runtime Auth actor. Later genuine triage UPDATEs do not take this path.
      return null;
    end if;
  end if;
  event_auth := private.intake_authenticated_subject();
  event_profile := private.current_subject_id();
  if tg_table_name = 'incidents' and tg_op = 'INSERT' then
    event_object := 'incident'; event_names := array['incident_created'];
    metadata := jsonb_build_object('incident_id', new.id, 'facility_id', new.facility_id);
  elsif tg_table_name = 'request_responses' and tg_op = 'INSERT' then
    event_object := 'request_response'; event_names := array['missing_information_received'];
    metadata := jsonb_build_object('request_id', new.request_id, 'facility_id', new.facility_id,
      'request_revision', new.request_revision);
  elsif tg_table_name = 'project_requests' and tg_op in ('INSERT', 'UPDATE') then
    event_object := 'project_request'; event_names := array[]::text[];
    metadata := jsonb_build_object('request_id', new.id, 'facility_id', new.facility_id,
      'incident_id', new.incident_id, 'revision', new.revision, 'status', new.status,
      'assigned_to_profile_id', new.assigned_to_profile_id,
      'classified_issue_id', new.classified_issue_id, 'classified_intent_id', new.classified_intent_id,
      'next_action_present', coalesce(char_length(btrim(new.next_action)) > 0, false));
    if tg_op = 'INSERT' then event_names := array['request_created', 'request_submitted'];
    else
      metadata := metadata || jsonb_build_object('previous_status', old.status,
        'previous_revision', old.revision, 'previous_assigned_to_profile_id', old.assigned_to_profile_id,
        'previous_classified_issue_id', old.classified_issue_id,
        'previous_classified_intent_id', old.classified_intent_id);
      if new.assigned_to_profile_id is distinct from old.assigned_to_profile_id then
        event_names := array_append(event_names, 'request_assigned'); end if;
      if new.classified_issue_id is distinct from old.classified_issue_id
        or new.classified_intent_id is distinct from old.classified_intent_id then
        event_names := array_append(event_names, 'request_reclassified'); end if;
      if new.status is distinct from old.status or new.next_action is distinct from old.next_action then
        event_names := array_append(event_names, 'request_status_changed'); end if;
    end if;
  else raise exception 'Unsupported intake audit relation' using errcode = '55000'; end if;
  foreach event_name in array event_names loop
    insert into public.audit_events (account_id, actor_user_profile_id, actor_kind,
      actor_auth_user_id, object_type, object_id, event_type, event_metadata,
      occurred_at, correlation_id, is_internal_only, is_demo)
    values (new.account_id, event_profile, 'user', event_auth, event_object, new.id,
      event_name, metadata, pg_catalog.clock_timestamp(), event_correlation, true, true);
  end loop;
  return null;
end;
$$;
create trigger incidents_audit after insert on public.incidents
  for each row execute function private.audit_intake_change();
create trigger project_requests_audit after insert or update on public.project_requests
  for each row execute function private.audit_intake_change();
create trigger request_responses_audit after insert on public.request_responses
  for each row execute function private.audit_intake_change();

create function private.intake_catalogue()
returns jsonb language plpgsql security definer set search_path = '' as $$
begin
  perform private.intake_authenticated_subject();
  return jsonb_build_object('version', '2026-10-08.1', 'issues', (
    select jsonb_agg(jsonb_build_object('id', id, 'label', label) order by id) from (values
      ('ISSUE-001', 'Fire / Smoke / Soot'), ('ISSUE-002', 'Water / Moisture / Flood'),
      ('ISSUE-003', 'Sewage / Contaminated Water'), ('ISSUE-004', 'Storm / Wind / Hail / Hurricane'),
      ('ISSUE-005', 'Mold / Microbial'), ('ISSUE-006', 'IAQ / Occupant Complaint'),
      ('ISSUE-007', 'Odor / Residue'), ('ISSUE-008', 'Chemical Concern'),
      ('ISSUE-009', 'Suspected Drug-Related Contamination'), ('ISSUE-010', 'Asbestos'),
      ('ISSUE-011', 'Lead'), ('ISSUE-012', 'Dust / Silica / Particulate'),
      ('ISSUE-013', 'VOC / Formaldehyde / Chemical Exposure'), ('ISSUE-014', 'Worker Exposure'),
      ('ISSUE-015', 'Regulated Materials Before Work'), ('ISSUE-016', 'General Property Condition'),
      ('ISSUE-017', 'Environmental Site / Soil / Groundwater / Vapor'),
      ('ISSUE-018', 'Healthcare Facility Incident'), ('ISSUE-019', 'Unknown / Help Classify')
    ) source(id, label)), 'intents', (
    select jsonb_agg(jsonb_build_object('id', id, 'label', label) order by id) from (values
      ('INTENT-001', 'Assess what is happening'), ('INTENT-002', 'Identify source/pathway/extent'),
      ('INTENT-003', 'Document affected areas'), ('INTENT-004', 'Evaluate a specific concern'),
      ('INTENT-005', 'Recommend whether testing is needed'), ('INTENT-006', 'Perform approved testing/sampling'),
      ('INTENT-007', 'Develop protocol or scope'), ('INTENT-008', 'Review existing report, estimate, or contractor scope'),
      ('INTENT-009', 'Review contractor work'), ('INTENT-010', 'Monitor or oversee work'),
      ('INTENT-011', 'Verify work after completion'), ('INTENT-012', 'Provide clearance-type assessment where applicable'),
      ('INTENT-013', 'Provide 3D documentation/measurements'), ('INTENT-014', 'Provide expert/dispute-level support'),
      ('INTENT-015', 'Provide consultation only'), ('INTENT-016', 'Help classify the request')
    ) source(id, label)), 'statuses', jsonb_build_array('submitted', 'intake_completeness_review',
      'needs_client_information', 'classification_review', 'technical_review', 'safety_review',
      'revision_proposed', 'client_revision_pending', 'declined', 'cancelled'));
end;
$$;

create function private.validate_intake_submission(p_submission jsonb)
returns void language plpgsql security invoker set search_path = '' as $$
declare item record; flag jsonb; incident jsonb;
begin
  if jsonb_typeof(p_submission) is distinct from 'object' then
    raise exception 'Invalid intake submission' using errcode = '22023'; end if;
  for item in select * from jsonb_each(p_submission) loop
    if item.key not in ('title','original_wording','issue_id','intent_id','urgency','affected_area',
      'site_contact','access_notes','safety_flags','payer_note','signer_note','incident_id','new_incident') then
      raise exception 'Invalid intake submission' using errcode = '22023'; end if;
    if item.key in ('title','original_wording','issue_id','intent_id','urgency','affected_area',
      'site_contact','access_notes','payer_note','signer_note') then
      if jsonb_typeof(item.value) <> 'string' or
        char_length(item.value #>> '{}') > (case item.key when 'title' then 160 when 'original_wording' then 8000 else 2000 end) then
        raise exception 'Invalid intake submission' using errcode = '22023'; end if;
    end if;
  end loop;
  if coalesce(char_length(btrim(p_submission ->> 'title')), 0) = 0
    or coalesce(char_length(btrim(p_submission ->> 'original_wording')), 0) = 0
    or coalesce(p_submission ->> 'issue_id', '') !~ '^ISSUE-(00[1-9]|01[0-9])$'
    or coalesce(p_submission ->> 'intent_id', '') !~ '^INTENT-(00[1-9]|01[0-6])$'
    or coalesce(p_submission ->> 'urgency', '') not in ('routine','urgent','emergency') then
    raise exception 'Invalid intake submission' using errcode = '22023'; end if;
  if p_submission ? 'safety_flags' then
    if jsonb_typeof(p_submission -> 'safety_flags') <> 'array' then
      raise exception 'Invalid intake submission' using errcode = '22023'; end if;
    if jsonb_array_length(p_submission -> 'safety_flags') > 20 then
      raise exception 'Invalid intake submission' using errcode = '22023'; end if;
    for flag in select value from jsonb_array_elements(p_submission -> 'safety_flags') loop
      if jsonb_typeof(flag) <> 'string' or char_length(btrim(flag #>> '{}')) = 0
        or char_length(flag #>> '{}') > 200 then
        raise exception 'Invalid intake submission' using errcode = '22023'; end if;
    end loop;
  end if;
  if p_submission ? 'incident_id' and p_submission ? 'new_incident' then
    raise exception 'Invalid intake submission' using errcode = '22023'; end if;
  if p_submission ? 'incident_id' then
    if jsonb_typeof(p_submission -> 'incident_id') <> 'string' then
      raise exception 'Invalid intake submission' using errcode = '22023'; end if;
    begin perform (p_submission ->> 'incident_id')::uuid;
    exception when invalid_text_representation then
      raise exception 'Invalid intake submission' using errcode = '22023'; end;
  end if;
  if p_submission ? 'new_incident' then
    incident := p_submission -> 'new_incident';
    if jsonb_typeof(incident) <> 'object' then
      raise exception 'Invalid intake submission' using errcode = '22023'; end if;
    if exists(select 1 from jsonb_object_keys(incident) k where k not in ('title','occurred_at'))
      or jsonb_typeof(incident -> 'title') is distinct from 'string'
      or char_length(btrim(incident ->> 'title')) = 0
      or char_length(incident ->> 'title') > 160 then
      raise exception 'Invalid intake submission' using errcode = '22023'; end if;
    if incident ? 'occurred_at' then
      if jsonb_typeof(incident -> 'occurred_at') <> 'string' or char_length(incident ->> 'occurred_at') > 64 then
        raise exception 'Invalid intake submission' using errcode = '22023'; end if;
      begin
        if not isfinite((incident ->> 'occurred_at')::timestamptz) then
          raise exception 'Invalid intake submission' using errcode = '22023'; end if;
      exception when invalid_datetime_format or datetime_field_overflow then
        raise exception 'Invalid intake submission' using errcode = '22023'; end;
    end if;
  end if;
end;
$$;

create function private.submit_project_request(p_account_id uuid, p_facility_id uuid,
  p_idempotency_key uuid, p_submission jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  actor_auth uuid := private.intake_authenticated_subject();
  actor_profile uuid := private.current_subject_id();
  existing public.project_requests%rowtype; new_id uuid; incident_id uuid;
begin
  if not private.lock_intake_profile(actor_profile, p_account_id, p_facility_id, 'submit_request') then
    raise exception 'Intake unavailable' using errcode = '42501'; end if;
  if p_idempotency_key is null then raise exception 'Invalid intake submission' using errcode = '22023'; end if;
  perform private.validate_intake_submission(p_submission);
  -- Serializes the account/subject/key (not the whole account). The unique index
  -- remains authoritative. Hash collisions only serialize unrelated requests.
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    p_account_id::text || '/' || actor_profile::text || '/' || p_idempotency_key::text, 0));
  select * into existing from public.project_requests where account_id = p_account_id
    and submitted_by_profile_id = actor_profile and idempotency_key = p_idempotency_key;
  if found then
    if existing.facility_id <> p_facility_id or existing.original_submission <> p_submission then
      raise exception 'Intake idempotency conflict' using errcode = '23505'; end if;
    return jsonb_build_object('request_id', existing.id, 'revision', 1, 'status', 'submitted');
  end if;
  if p_submission ? 'incident_id' then
    incident_id := (p_submission ->> 'incident_id')::uuid;
    perform 1 from public.incidents where id = incident_id and account_id = p_account_id
      and facility_id = p_facility_id and is_demo for share;
    if not found then raise exception 'Intake unavailable' using errcode = '42501'; end if;
  elsif p_submission ? 'new_incident' then
    insert into public.incidents (account_id, facility_id, title, occurred_at,
      created_by_profile_id, created_by_auth_user_id)
    values (p_account_id, p_facility_id, p_submission #>> '{new_incident,title}',
      (p_submission #>> '{new_incident,occurred_at}')::timestamptz, actor_profile, actor_auth)
    returning id into incident_id;
  end if;
  insert into public.project_requests (account_id, facility_id, incident_id,
    submitted_by_profile_id, submitted_by_auth_user_id, idempotency_key, original_submission,
    title, original_wording, original_issue_id, original_intent_id, catalogue_version,
    urgency, status)
  values (p_account_id, p_facility_id, incident_id, actor_profile, actor_auth, p_idempotency_key,
    p_submission, p_submission ->> 'title', p_submission ->> 'original_wording',
    p_submission ->> 'issue_id', p_submission ->> 'intent_id', '2026-10-08.1',
    p_submission ->> 'urgency', 'submitted') returning id into new_id;
  return jsonb_build_object('request_id', new_id, 'revision', 1, 'status', 'submitted');
end;
$$;

create function private.intake_request_item(p_request public.project_requests, p_detail boolean)
returns jsonb language sql stable security invoker set search_path = '' as $$
  select jsonb_build_object('id', p_request.id, 'account_id', p_request.account_id,
    'facility_id', p_request.facility_id, 'incident_id', p_request.incident_id,
    'title', p_request.title, 'original_wording', p_request.original_wording,
    'original_issue_id', p_request.original_issue_id, 'original_intent_id', p_request.original_intent_id,
    'classified_issue_id', p_request.classified_issue_id, 'classified_intent_id', p_request.classified_intent_id,
    'catalogue_version', p_request.catalogue_version, 'urgency', p_request.urgency,
    'status', p_request.status, 'revision', p_request.revision,
    'assigned_to_profile_id', p_request.assigned_to_profile_id, 'next_action', p_request.next_action,
    'created_at', p_request.created_at, 'updated_at', p_request.updated_at,
    'can_triage', p_request.status in ('submitted', 'intake_completeness_review', 'needs_client_information',
      'classification_review', 'technical_review', 'safety_review', 'revision_proposed', 'client_revision_pending')
      and private.intake_profile_access(private.current_subject_id(), p_request.account_id, p_request.facility_id, 'triage_request'),
    'can_respond', p_request.status = 'needs_client_information'
      and p_request.submitted_by_profile_id is not distinct from private.current_subject_id()
      and private.intake_profile_access(private.current_subject_id(), p_request.account_id, p_request.facility_id, null))
    || case when p_detail then jsonb_build_object('original_submission', p_request.original_submission,
      'responses', coalesce((select jsonb_agg(jsonb_build_object('id', r.id, 'body', r.body,
        'created_at', r.created_at) order by r.created_at, r.id) from public.request_responses r
        where r.request_id = p_request.id), '[]'::jsonb)) else '{}'::jsonb end
$$;

create function private.list_project_requests(p_account_id uuid, p_after_id uuid default null,
  p_limit integer default 50, p_status text default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare profile_id uuid; result jsonb; next_id uuid;
begin
  perform private.intake_authenticated_subject(); profile_id := private.current_subject_id();
  if p_limit is null or p_limit not between 1 and 100 or (p_status is not null and
    not (private.intake_catalogue() -> 'statuses') ? p_status) then
    raise exception 'Invalid intake query' using errcode = '22023'; end if;
  with permitted as (
    select r.* from public.project_requests r where r.account_id = p_account_id and r.is_demo
      and (p_after_id is null or r.id > p_after_id) and (p_status is null or r.status = p_status)
      and private.intake_profile_access(profile_id, r.account_id, r.facility_id, null)
      and (r.submitted_by_profile_id = profile_id
        or private.intake_profile_access(profile_id, r.account_id, r.facility_id, 'triage_request'))
    order by r.id limit p_limit + 1
  ), numbered as (select p.*, row_number() over (order by p.id) ordinal from permitted p)
  select coalesce(jsonb_agg(private.intake_request_item(r, false) order by r.id)
      filter (where n.ordinal <= p_limit), '[]'::jsonb),
    case when count(*) > p_limit then (array_agg(r.id order by r.id))[p_limit] else null end
    into result, next_id from numbered n join public.project_requests r on r.id = n.id;
  return jsonb_build_object('items', result, 'next_cursor', next_id);
end;
$$;

create function private.get_project_request(p_request_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare r public.project_requests%rowtype; profile_id uuid;
begin
  perform private.intake_authenticated_subject(); profile_id := private.current_subject_id();
  select * into r from public.project_requests where id = p_request_id and is_demo;
  if not found or not private.intake_profile_access(profile_id, r.account_id, r.facility_id, null)
    or not (r.submitted_by_profile_id is not distinct from profile_id
      or private.intake_profile_access(profile_id, r.account_id, r.facility_id, 'triage_request')) then return null; end if;
  return private.intake_request_item(r, true);
end;
$$;

create function private.list_intake_assignees(p_account_id uuid, p_facility_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare result jsonb;
begin
  perform private.intake_authenticated_subject();
  if not private.intake_profile_access(private.current_subject_id(), p_account_id, p_facility_id, 'triage_request') then
    raise exception 'Intake unavailable' using errcode = '42501'; end if;
  select coalesce(jsonb_agg(jsonb_build_object('profile_id', p.id, 'display_name', p.display_name)
    order by p.id), '[]'::jsonb) into result from public.user_profiles p
    where private.intake_profile_access(p.id, p_account_id, p_facility_id, 'triage_request');
  return result;
end;
$$;

create function private.triage_project_request(p_request_id uuid, p_expected_revision bigint, p_changes jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare r public.project_requests%rowtype; revised public.project_requests%rowtype;
  profile_id uuid; item record;
begin
  perform private.intake_authenticated_subject(); profile_id := private.current_subject_id();
  select * into r from public.project_requests where id = p_request_id and is_demo;
  if not found or not private.lock_intake_profile(profile_id, r.account_id, r.facility_id, 'triage_request') then
    raise exception 'Intake unavailable' using errcode = '42501'; end if;
  if jsonb_typeof(p_changes) is distinct from 'object' or p_changes = '{}'::jsonb then
    raise exception 'Invalid intake change' using errcode = '22023'; end if;
  for item in select * from jsonb_each(p_changes) loop
    if item.key not in ('assigned_to_profile_id','status','classified_issue_id','classified_intent_id','next_action')
      or jsonb_typeof(item.value) not in ('string','null') then
      raise exception 'Invalid intake change' using errcode = '22023'; end if;
  end loop;
  -- Re-read under a row lock after authorization locks: one revision wins.
  select * into r from public.project_requests where id = p_request_id for update;
  if p_expected_revision is null or p_expected_revision <> r.revision then
    raise exception 'Stale intake revision' using errcode = '40001'; end if;
  revised := r;
  if p_changes ? 'assigned_to_profile_id' then
    begin revised.assigned_to_profile_id := (p_changes ->> 'assigned_to_profile_id')::uuid;
    exception when invalid_text_representation then
      raise exception 'Invalid intake change' using errcode = '22023'; end;
  end if;
  if p_changes ? 'status' then revised.status := p_changes ->> 'status'; end if;
  if p_changes ? 'classified_issue_id' then revised.classified_issue_id := p_changes ->> 'classified_issue_id'; end if;
  if p_changes ? 'classified_intent_id' then revised.classified_intent_id := p_changes ->> 'classified_intent_id'; end if;
  if p_changes ? 'next_action' then revised.next_action := p_changes ->> 'next_action'; end if;
  if revised.assigned_to_profile_id is not null and not private.lock_intake_profile(
    revised.assigned_to_profile_id, r.account_id, r.facility_id, 'triage_request') then
    raise exception 'Intake unavailable' using errcode = '42501'; end if;
  if r.status not in ('submitted', 'intake_completeness_review', 'needs_client_information',
    'classification_review', 'technical_review', 'safety_review', 'revision_proposed', 'client_revision_pending')
    or revised.status is null
    or (revised.status <> r.status and not private.intake_transition_allowed(r.status, revised.status))
    or (revised.classified_issue_id is not null and revised.classified_issue_id !~ '^ISSUE-(00[1-9]|01[0-9])$')
    or (revised.classified_intent_id is not null and revised.classified_intent_id !~ '^INTENT-(00[1-9]|01[0-6])$')
    or char_length(revised.next_action) > 2000
    or (revised.status = 'needs_client_information' and (revised.assigned_to_profile_id is null
      or coalesce(char_length(btrim(revised.next_action)), 0) = 0)) then
    raise exception 'Invalid intake change' using errcode = '22023'; end if;
  if revised is not distinct from r then
    return jsonb_build_object('request_id', r.id, 'revision', r.revision, 'status', r.status); end if;
  update public.project_requests set assigned_to_profile_id = revised.assigned_to_profile_id,
    status = revised.status, classified_issue_id = revised.classified_issue_id,
    classified_intent_id = revised.classified_intent_id, next_action = revised.next_action,
    revision = r.revision + 1 where id = r.id returning * into r;
  return jsonb_build_object('request_id', r.id, 'revision', r.revision, 'status', r.status);
end;
$$;

create function private.respond_project_request(p_request_id uuid, p_expected_revision bigint, p_response text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare r public.project_requests%rowtype; actor_auth uuid := private.intake_authenticated_subject();
  profile_id uuid := private.current_subject_id();
begin
  select * into r from public.project_requests where id = p_request_id and is_demo;
  if not found or r.submitted_by_profile_id is distinct from profile_id
    or not private.lock_intake_profile(profile_id, r.account_id, r.facility_id, null) then
    raise exception 'Intake unavailable' using errcode = '42501'; end if;
  select * into r from public.project_requests where id = p_request_id for update;
  if p_expected_revision is null or p_expected_revision <> r.revision then
    raise exception 'Stale intake revision' using errcode = '40001'; end if;
  if r.status <> 'needs_client_information' or p_response is null
    or char_length(btrim(p_response)) = 0 or char_length(p_response) > 8000 then
    raise exception 'Invalid intake response' using errcode = '22023'; end if;
  update public.project_requests set status = 'intake_completeness_review', revision = r.revision + 1
    where id = r.id returning * into r;
  insert into public.request_responses (request_id, account_id, facility_id,
    submitted_by_profile_id, submitted_by_auth_user_id, body, request_revision)
  values (r.id, r.account_id, r.facility_id, profile_id, actor_auth, p_response, r.revision);
  return jsonb_build_object('request_id', r.id, 'revision', r.revision, 'status', r.status);
end;
$$;

-- Minimal public invoker wrappers; all privileged code lives in non-exposed
-- private, validates gateway provenance, and checks current database authority.
create function public.intake_catalogue() returns jsonb
language sql security invoker set search_path = '' as $$ select private.intake_catalogue() $$;
create function public.submit_project_request(p_account_id uuid, p_facility_id uuid,
  p_idempotency_key uuid, p_submission jsonb) returns jsonb
language sql security invoker set search_path = '' as $$
  select private.submit_project_request(p_account_id,p_facility_id,p_idempotency_key,p_submission) $$;
create function public.list_project_requests(p_account_id uuid, p_after_id uuid default null,
  p_limit integer default 50, p_status text default null) returns jsonb
language sql security invoker set search_path = '' as $$
  select private.list_project_requests(p_account_id,p_after_id,p_limit,p_status) $$;
create function public.get_project_request(p_request_id uuid) returns jsonb
language sql security invoker set search_path = '' as $$ select private.get_project_request(p_request_id) $$;
create function public.list_intake_assignees(p_account_id uuid, p_facility_id uuid) returns jsonb
language sql security invoker set search_path = '' as $$ select private.list_intake_assignees(p_account_id,p_facility_id) $$;
create function public.triage_project_request(p_request_id uuid, p_expected_revision bigint, p_changes jsonb) returns jsonb
language sql security invoker set search_path = '' as $$ select private.triage_project_request(p_request_id,p_expected_revision,p_changes) $$;
create function public.respond_project_request(p_request_id uuid, p_expected_revision bigint, p_response text) returns jsonb
language sql security invoker set search_path = '' as $$ select private.respond_project_request(p_request_id,p_expected_revision,p_response) $$;

revoke all on function private.intake_authenticated_subject(),
  private.request_from_legacy(public.incident_requests), private.intake_seed_context(),
  private.is_canonical_intake_seed(public.incident_requests), private.import_canonical_intake_seed(),
  private.link_canonical_intake_seed_document(),
  private.intake_profile_access(uuid,uuid,uuid,text), private.lock_intake_profile(uuid,uuid,uuid,text),
  private.intake_transition_allowed(text,text), private.guard_intake_history(), private.audit_intake_change(),
  private.validate_intake_submission(jsonb), private.intake_request_item(public.project_requests,boolean),
  private.intake_catalogue(), private.submit_project_request(uuid,uuid,uuid,jsonb),
  private.list_project_requests(uuid,uuid,integer,text), private.get_project_request(uuid),
  private.list_intake_assignees(uuid,uuid), private.triage_project_request(uuid,bigint,jsonb),
  private.respond_project_request(uuid,bigint,text),
  public.intake_catalogue(), public.submit_project_request(uuid,uuid,uuid,jsonb),
  public.list_project_requests(uuid,uuid,integer,text), public.get_project_request(uuid),
  public.list_intake_assignees(uuid,uuid), public.triage_project_request(uuid,bigint,jsonb),
  public.respond_project_request(uuid,bigint,text)
  from public, anon, authenticated, service_role;
grant execute on function private.intake_catalogue(), private.submit_project_request(uuid,uuid,uuid,jsonb),
  private.list_project_requests(uuid,uuid,integer,text), private.get_project_request(uuid),
  private.list_intake_assignees(uuid,uuid), private.triage_project_request(uuid,bigint,jsonb),
  private.respond_project_request(uuid,bigint,text),
  public.intake_catalogue(), public.submit_project_request(uuid,uuid,uuid,jsonb),
  public.list_project_requests(uuid,uuid,integer,text), public.get_project_request(uuid),
  public.list_intake_assignees(uuid,uuid), public.triage_project_request(uuid,bigint,jsonb),
  public.respond_project_request(uuid,bigint,text) to authenticated;

comment on table public.project_requests is
  'Synthetic intake only. Original submission and tenant/facility are immutable. Current classification/assignment/review state confer no professional, commercial, project or mobilization authority. Legacy UUIDs resolve through the same checked RPC.';
comment on table public.incidents is 'Optional synthetic event context, not a request or project. No inferred incident was backfilled.';
comment on column public.documents.project_request_id is 'Additive request link; old incident_request_id remains intact and readable to authorized future document workflows.';
comment on function public.triage_project_request(uuid,bigint,jsonb) is
  'Review routing only. Current exact-facility triage capability and optimistic revision required; no technical approval, accepted scope, agreement or scheduling state.';

commit;
